services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      - mkdi-staging
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www:/var/www/certbot/:ro
      - ./certs/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./www/:/var/www/certbot/:rw
      - ./certs/:/etc/letsencrypt/:rw

networks:
  mkdi-staging:
    external: true
